name: Magdalena Groszek
favicon: null
layout_spectrum: 0.998222284950316
typography_spectrum: 0.6462154053151608
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c6c5c1'
    - '#b2afa9'
    - '#a29f99'
    - '#e8e7e3'
    - '#86817c'
  brandStrength: 0.6875
  lightness: 0.6301112161017954
  saturation: 0.8827907294034958
  rhythmicContrast: 0.25085047679021955
purpose: []
